name: Man10Crafting
version: '1.0'
main: tororo1066.man10crafting.Man10Crafting
api-version: '1.21'
loader: tororo1066.man10crafting.DependencyLoader

dependencies:
  server:
    NBTAPI:
      load: BEFORE
      required: false
      join-classpath: true
    StopCraftCMDV2:
      load: BEFORE
      required: true
      join-classpath: true